package com.example.spinner

enum class Roles(val rus: String) {
    SOFTWARE_ENGINEER("Инженер-программист"),
    DATA_SCIENTIST("Специалист по данным"),
    SYSTEM_ADMINISTRATOR("Системный администратор"),
    DATABASE_ADMINISTRATOR("Администратор базы данных"),
    NETWORK_ENGINEER("Сетевой инженер"),
    DEVOPS_ENGINEER("Инженер DevOps"),
    SECURITY_ANALYST("Аналитик по безопасности"),
    CLOUD_ARCHITECT("Облачный архитектор"),
    MOBILE_DEVELOPER("Разработчик мобильных приложений"),
    FRONTEND_DEVELOPER("Frontend разработчик"),
    BACKEND_DEVELOPER("Backend разработчик"),
    FULLSTACK_DEVELOPER("Fullstack разработчик"),
    IT_MANAGER("ИТ менеджер"),
    IT_SUPPORT_SPECIALIST("Специалист по поддержке ИТ"),
    BUSINESS_ANALYST("Бизнес-аналитик"),
    QA_ENGINEER("Инженер по качеству"),
    PRODUCT_MANAGER("Менеджер продукта"),
    PROJECT_MANAGER("Менеджер проекта"),
    UX_UI_DESIGNER("UX/UI дизайнер"),
    SCRUM_MASTER("Scrum мастер"),
    TECHNICAL_WRITER("Технический писатель"),
    SOLUTIONS_ARCHITECT("Архитектор решений"),
    MACHINE_LEARNING_ENGINEER("Инженер по машинному обучению"),
    ARTIFICIAL_INTELLIGENCE_ENGINEER("Инженер по искусственному интеллекту"),
    CYBERSECURITY_ENGINEER("Инженер по кибербезопасности"),
    SITE_RELIABILITY_ENGINEER("Инженер надежности сайта"),
    CHIEF_TECHNOLOGY_OFFICER("Технический директор"),
    CHIEF_INFORMATION_OFFICER("Директор по информационным технологиям"),
    CHIEF_INFORMATION_SECURITY_OFFICER("Директор по информационной безопасности"),
    IT_CONSULTANT("ИТ консультант")
}